"use client"

import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { GlobalStyles } from '@/styles/GlobalStyles'
import Checkout from './checkout/page'
import Home from './home/page'
import { OrderContextProvider } from '@/contexts/OrderContext'

const inter = Inter({ subsets: ['latin'] })

// export const metadata: Metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// }

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="pt-BR">
      <OrderContextProvider>
      <GlobalStyles />
      <body>{children}</body>
      </OrderContextProvider>
    </html>
  )
}
